name: Publish to CurseForge

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Publish to CurseForge
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          curseforge-id: "1689153"
          curseforge-token: "${{ secrets.CURSEFORGE_TOKEN }}"

          files: "*.jar|!*-sources.jar|!*-dev.jar"

          name: "${{ github.event.release.name }}"
          version: "${{ github.event.release.tag_name }}"
          version-type: release
          changelog: "${{ github.event.release.body }}"
          changelog-type: markdown
          loaders: fabric
          game-versions: "26.2"
          java: "25"
          dependencies: |
            fabric-api
            litematica
